# -*- coding: utf-8 -*-
"""Accidents.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x_7s3kOGLozTbNLMzmOdDjuSOnnpRhNf
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error
import matplotlib.pyplot as plt
df=pd.read_csv('/content/Accidents.csv')
df=df.dropna()
x=df[['Vehicle speed(km/h)','Potholes', 'Manufacture year']]
y=df['Accident severity']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=1)
regressor=LinearRegression()
regressor.fit(x_train, y_train)
y_pred=regressor.predict(x_test)
mse=mean_squared_error(y_test, y_pred)
mae=mean_absolute_error(y_test, y_pred)
print('Mean squared err:', mse)
print('mean abslute err:', mae)
#new data
new_data=np.array([55,1,2023])
predicted_severity=regressor.predict([new_data])
print('Accident severity:', predicted_severity)
import joblib
joblib.dump(regressor,'Accident_severity_predictor.pkl')